### ISSUE TITLE
which R version does riborex support?

### ISSUE THREAD

**Issue by how-wonderful** [smithlabcode/riborex#1]
I'm trying to install riborex following the README and got this:

```
Warning in install.packages :
  package ‘riborex-1.2.3.tar.gz’ is not available (for R version 3.3.1)
```

Which version of R does riborex support?
Thanks!

**Comment by wenzhenl** [comment]
We've tested it with R version 3.3.1 with Ubuntu 12.04 and macOS EI Capitan, so what os are you using?

**Comment by how-wonderful** [comment]
os x Yosemite... that is weird...

**Comment by wenzhenl** [comment]
Thanks for your feedback. I just checked with Yosemite, I found that if I try to install from R studio, the same warning info appears, but if I install from a terminal it just reminds you that you have to install DESeq2 and edgeR first. Have you installed the dependencies yet? I will check to see why R studio didn't give the dependency info.

**Comment by how-wonderful** [comment]
yes I have installed the two dependencies

**Comment by wenzhenl** [comment]
And you are installing from a terminal?

**Comment by wenzhenl** [comment]
Please use 
`install.packages("riborex-1.2.3.tar.gz", type="source")`

I just tested it on a Yosemite machine and it works.
But with Ubuntu 12.04 and mac EI Capitan, without type="source" also works, weird...

**Comment by how-wonderful** [comment]
Yeah it is a problem of Rstudio. I used R.app to install it and it worked. Thanks!
