### ISSUE TITLE
Filtering options as in DESeq?

### ISSUE THREAD

**Issue by marencc** [smithlabcode/riborex#3]
Hello developer! 
I'm trying your riborex for some ribo-seq data/rnaseq data that I have. 
In my typical rnaseq workflow, as I work with stringTie-prepDe.py, I would make a DeseqDataSet object with DESeqDataSetFromMatrix. Then, I would apply, if necessary, a filter such as:
#dds <- dds [rowSums(counts(dds))>1, ]
or
#keep <- rowSums(counts(dds) >= 5) >= 3
#dds <- dds[keep,] 
if I wish to remove the genes that have all 0's or so, else, I would
#dds <- dds [rowVars(counts(dds))>1, ] 
to keep those genes that have (>1) variability. 

I would then, revel so that the $condition in the dds object is correctly chosen. 

Just after doing all of this, I would use the DESeq(dds) function. 

I was wondering, if you took into consideration these or any other type of "data filtering" techniques. If so, how can I apply them? Or else, I would like to double check, if I filter over the DESeqDataSet object and then feed the filtered data with counts(dds) or assay(dds)

as appropiate for:
RNACntTable or 
RiboCntTable

would that be ok? 

Many thanks for your support, 

MECC

**Comment by wenzhenl** [comment]
Hi,

In Riborex, we have option ``minMeanCount`` to remove the genes that have mean read count less than minMeanCount. If that cannot satisfy the data filtering you want to have, then you can do the data filtering in advance, and feed the filtered data as ``RNACntTable`` and ``RiboCntTable``, just make sure the filtered gene sets are the same for RNA and Ribo-seq data and in the same order.

**Comment by marencc** [comment]
Ok, Many thanks, I've located the "minMeancount" in the riborex function. 

Additionally, this means that if I choose to do my own filtering, then I'd  have to check that the gene sets between are properly shared (and in the same order). Ok I didn't know I had to take that into account, but it is obviously necessary to have the same gene sets.  
cheers

**Comment by marencc** [comment]
Sorry, just one more question, what about the correct levels for control/treatment? I usually do "relevel" to make sure my control (which doesn't necessarily have the name 'control') is used as the "base" to compare the FC. 
Many thanks

**Comment by wenzhenl** [comment]
I'm not sure if I understood your question correctly. But in my understanding the names of levels don't really matter here. Just make sure the samples in the same condition use the same label (not necessarily "control" or "treated") and it's the order of samples that determines the "base" used to compare the FC, in two condition experiment, the first level is used as the "base" to compare against.

cheers
