### ISSUE TITLE
RNA-seq and RIBO-seq do not have replicates.

### ISSUE THREAD

**Issue by junjunlab** [smithlabcode/riborex#9]
Thank you for your great package to analysis differential translation events on ribo-seq data. I am using your package to analysis my own data,but my rnaseq and riboseq data do not have replicates,how can i use this package to find differential translation genes ? I am looking forward to your reply!

**Comment by wenzhenl** [comment]
Hi, 

Unfortunately, riborex does not support analysis with no replicates.
